version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: mysql_dev
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - dev_network

  backend:
    container_name: backend_dev
    build:
      context: ./backend
      dockerfile: Dockerfile # Será ajustado para multi-stage
      target: development # Assumindo Dockerfile multi-stage posteriormente
    env_file:
      - ./backend/.env.dev
    ports:
      - "3001:3001"
    volumes:
      - ./backend:/app # Monta o código para hot-reloading
      - /app/node_modules # Evita sobrescrever node_modules
    depends_on:
      - mysql
    networks:
      - dev_network
    command: npm run start:dev # Comando de desenvolvimento do NestJS

  frontend:
    container_name: frontend_dev
    build:
      context: ./frontend
      dockerfile: Dockerfile # Será ajustado para multi-stage
      target: development # Assumindo Dockerfile multi-stage posteriormente
    env_file:
      - ./frontend/.env.dev
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app # Monta o código para hot-reloading
      - /app/node_modules # Evita sobrescrever node_modules
    networks:
      - dev_network
    command: npm run dev

networks:
  dev_network:
    driver: bridge

volumes:
  mysql_data:

