version: '3.8'

services:
  backend:
    container_name: backend_prod
    build:
      context: ./backend
      dockerfile: Dockerfile # Será ajustado para multi-stage
      target: production
    env_file:
      - ./backend/.env.prod
    networks:
      - prod_network
    restart: unless-stopped
    # Não expõe porta diretamente, NGINX fará o proxy

  frontend:
    container_name: frontend_prod
    build:
      context: ./frontend
      dockerfile: Dockerfile # Será ajustado para multi-stage
      target: production
    env_file:
      - ./frontend/.env.prod
    networks:
      - prod_network
    restart: unless-stopped
    environment:
      - NEXT_PUBLIC_API_URL=/api
    # Não expõe porta diretamente, NGINX fará o proxy

  nginx:
    container_name: nginx_proxy
    build:
      context: ./nginx # Diretório a ser criado com Dockerfile e nginx.conf
      dockerfile: Dockerfile
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  # Volume para persistir o nginx.conf
      - ./nginx/certificates:/etc/letsencrypt      # Volume para persistir os certificados SSL
    ports:
      - "443:443" # Expor porta 443 (HTTPS)
    depends_on:
      - backend
      - frontend
    networks:
      - prod_network
    restart: unless-stopped

networks:
  prod_network:
    driver: bridge
