@Cookie = access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImZhYTU5YWQyLTVlMTQtNDEwYi05YWIyLTY3ODUwY2YzMWQxZSIsIm5hbWUiOiJGw6FiaW8gTW9yZWlyYSIsImVtYWlsIjoiYWRtaW5AbWFjZWRvbWFjZWRvLmNvbSIsInBob25lIjoiKzU1NDY1OTAwOTc3OSIsInJvbGUiOiJBRE1JTiIsImVtYWlsVmVyaWZpZWQiOnRydWUsImxpY2Vuc2VOdW1iZXIiOm51bGwsImxpY2Vuc2VDYXRlZ29yeSI6bnVsbCwibGljZW5zZUV4cGlyYXRpb24iOm51bGwsImJyYW5jaElkIjpudWxsLCJjb21wYW55SWQiOiI5OGRhMzZkOC1lZGNiLTQzZTEtODVkYy1mMTlkMDA0MjE3MDYiLCJjcmVhdGVkQXQiOiIyMDI1LTA1LTI2VDIxOjQ5OjQyLjM0NVoiLCJ1cGRhdGVkQXQiOiIyMDI1LTA1LTI2VDIxOjQ5OjQyLjM0NVoiLCJpYXQiOjE3NDg4Mjg2MDUsImV4cCI6MTc0ODkxNTAwNX0.SoXPt6T-tCQgObZq6Vo0HLHRYHWeeJU0pSw2o4pNWLY

### Fazer login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@macedomacedo.com",
  "password": "password123"
}

### teste https://fivecoresolutions.com/api
POST https://fivecoresolutions.com/api/auth/login
Content-Type: application/json

{
  "email": "admin@saraivabatista.com",
  "password": "password123"
}

### Dados do usuário
GET http://localhost:3001/auth/me
Content-Type: application/json
Cookie: {{Cookie}}

### Buscar veículos
GET http://localhost:3001/vehicles
Cookie: {{Cookie}}

###Buscar ordens de uma compania
GET http://localhost:3001/orders
Cookie: {{Cookie}}

### Buscar ordens de um veículo
GET http://localhost:3001/orders/?plate=RV54JNI64
Cookie: {{Cookie}}

### Buscar veículo pela placa
GET http://localhost:3001/vehicles/RH84AOG
Cookie: {{Cookie}}

### Buscar todas as branchs
GET http://localhost:3001/branchs/
Cookie: {{Cookie}}

### Buscar todas as workshops
GET http://localhost:3001/workshops/
Cookie: {{Cookie}}

### Buscar todas as workshops e veículos em manutenção
GET http://localhost:3001/workshops/vehicles/
Cookie: {{Cookie}}

### Buscar workshop by id
GET http://localhost:3001/workshops/114f45a8-d799-41bc-8c5e-5dd3abd69956
Cookie: {{Cookie}}

### Criar novo veículo
POST http://localhost:3001/vehicles
Cookie: {{Cookie}}
Content-Type: application/json

{
  "plate": "ABC-1234",
  "branchId": 31,
  "model": "Civic",
  "brand": "Honda",
  "modelYear": 2023,
  "manufactureYear": 2022,
  "color": "Preto",
  "renavam": "12345678901",
  "chassis": "9BWZZZ377VT004251",
  "status": "AVAILABLE",
  "mileageStart": 0
}