@Cookie1 = access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjMwNGI1OGEwLThhZjYtNDc0OS04ZmIwLTM5ZjAxYjY3MWQ4MiIsIm5hbWUiOiJBZG1pbiBFbXByZXNhIDEiLCJlbWFpbCI6ImFkbWluMUBlbXByZXNhLmNvbSIsInBob25lIjoiMTE5MDAwMDAwMDEiLCJyb2xlIjoiQURNSU4iLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwicmVzZXRQYXNzd29yZFRva2VuIjpudWxsLCJyZXNldFBhc3N3b3JkRXhwaXJlcyI6bnVsbCwibGljZW5zZU51bWJlciI6bnVsbCwibGljZW5zZUNhdGVnb3J5IjpudWxsLCJsaWNlbnNlRXhwaXJhdGlvbiI6bnVsbCwiYnJhbmNoSWQiOjEsImNvbXBhbnlJZCI6ImJiNThkYWE3LTFlYmUtNDU2OC05NDFlLTM3NzZiZjRmOTNjMCIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMTVUMjM6Mjc6MTguMjg3WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMTVUMjM6Mjc6MTguMjg3WiIsImlhdCI6MTc0NzQyMzUwOSwiZXhwIjoxNzQ3NTA5OTA5fQ.bFy1FxiAxmPgqg2VrA7kFw3EtFHk3MhF_x9nGmcgqTk
@Cookie2 = access_token=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjgxZjY5N2NlLWEyODMtNDJlMi05Y2M5LTZiMjAwMDY4MjA5MyIsIm5hbWUiOiJBZG1pbiBFbXByZXNhIDIiLCJlbWFpbCI6ImFkbWluMkBlbXByZXNhLmNvbSIsInBob25lIjoiMTE5MDAwMDAwMDIiLCJyb2xlIjoiQURNSU4iLCJlbWFpbFZlcmlmaWVkIjpmYWxzZSwicmVzZXRQYXNzd29yZFRva2VuIjpudWxsLCJyZXNldFBhc3N3b3JkRXhwaXJlcyI6bnVsbCwibGljZW5zZU51bWJlciI6bnVsbCwibGljZW5zZUNhdGVnb3J5IjpudWxsLCJsaWNlbnNlRXhwaXJhdGlvbiI6bnVsbCwiYnJhbmNoSWQiOjcsImNvbXBhbnlJZCI6IjU1YzhiNjI5LWU3NjctNGEyNS04OWE2LTU1ZjUxODA2ZDIzYyIsImNyZWF0ZWRBdCI6IjIwMjUtMDUtMTVUMjM6Mjc6MTkuMDc1WiIsInVwZGF0ZWRBdCI6IjIwMjUtMDUtMTVUMjM6Mjc6MTkuMDc1WiIsImlhdCI6MTc0NzQyMzkyMCwiZXhwIjoxNzQ3NTEwMzIwfQ.WX-S-wAcdCq8VpphsTczQ8o6CKcc7TLxbOsfSAb0GUA
### Fazer login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin2@empresa.com",
  "password": "admin123"
}

### Buscar veículos
GET http://localhost:3001/vehicles
Cookie: {{Cookie2}}


### Buscar ordens de um veículo
GET http://localhost:3001/orders/plate/ABC2005
Cookie: {{Cookie2}}

###
GET http://localhost:3001/vehicles/ABC2005
Cookie: {{Cookie2}}
