@Cookie = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6ImFlMWU5M2JiLWQ4NjctNDc5Zi04NTUwLTZlYzcyYTdmYTk2NSIsIm5hbWUiOiJSb2JlcnRvIFhhdmllciBKci4iLCJlbWFpbCI6ImFkbWluQHNhcmFpdmFiYXRpc3RhLmNvbSIsInBob25lIjoiKzU1NzY3OTA3NzgyMjciLCJyb2xlIjoiQURNSU4iLCJlbWFpbFZlcmlmaWVkIjp0cnVlLCJsaWNlbnNlTnVtYmVyIjpudWxsLCJsaWNlbnNlQ2F0ZWdvcnkiOm51bGwsImxpY2Vuc2VFeHBpcmF0aW9uIjpudWxsLCJicmFuY2hJZCI6bnVsbCwiY29tcGFueUlkIjoiZjQyYWYyZDctYTE5OS00NGNmLTkwMDAtOWQwYzJkNThlMDNiIiwiY3JlYXRlZEF0IjoiMjAyNS0wNS0yNlQyMDoxNzo0NC44NzlaIiwidXBkYXRlZEF0IjoiMjAyNS0wNS0yNlQyMDoxNzo0NC44NzlaIiwiaWF0IjoxNzQ4NDU2Mjc4LCJleHAiOjE3NDg0NTk4Nzh9.CiFtYOm60TtooHmCUHOXa1ygmC06w2-IOE41fBjl9WY
### Fazer login
POST http://localhost:3001/auth/login
Content-Type: application/json

{
  "email": "admin@macedomacedo.com",
  "password": "password123"
}

### teste https://fivecoresolutions.com/api
POST https://fivecoresolutions.com/api/auth/login
Content-Type: application/json

{
  "email": "admin@saraivabatista.com",
  "password": "password123"
}

### Dados do usuário
GET http://localhost:3001/auth/me
Content-Type: application/json
Cookie: {{Cookie}}

### Buscar veículos
GET http://localhost:3001/vehicles
Cookie: {{Cookie}}

###Buscar ordens de uma compania
GET http://localhost:3001/orders
Cookie: {{Cookie}}

### Buscar ordens de um veículo
GET http://localhost:3001/orders/?plate=RV54JNI64
Cookie: {{Cookie}}

### Buscar veículo pela placa
GET http://localhost:3001/vehicles/RH84AOG
Cookie: {{Cookie}}

### Buscar todas as branchs
GET http://localhost:3001/branchs/
Cookie: {{Cookie}}

### Buscar todas as workshops
GET http://localhost:3001/workshops/
Cookie: {{Cookie}}

### Buscar todas as workshops e veículos em manutenção
GET http://localhost:3001/workshops/vehicles/
Cookie: {{Cookie}}

### Criar novo veículo
POST http://localhost:3001/vehicles
Cookie: {{Cookie}}
Content-Type: application/json

{
  "plate": "ABC-1234",
  "branchId": 31,
  "model": "Civic",
  "brand": "Honda",
  "modelYear": 2023,
  "manufactureYear": 2022,
  "color": "Preto",
  "renavam": "12345678901",
  "chassis": "9BWZZZ377VT004251",
  "status": "AVAILABLE",
  "mileageStart": 0
}