user  nginx;
worker_processes  auto;

error_log  /var/log/nginx/error.log warn;
pid        /var/run/nginx.pid;

events {
    worker_connections 1024;
}

http {
    include       /etc/nginx/mime.types;
    default_type  application/octet-stream;

    # Seu bloco HTTP (porta 80)
    server {
        listen 80;
        server_name fivecoresolutions.com www.fivecoresolutions.com;  # Substitua pelo seu domínio

        # Redireciona todas as requisições HTTP para HTTPS
        return 301 https://$host$request_uri;
    }

    # Seu bloco HTTPS (porta 443)
    server {
        listen 443 ssl;
	    http2 on;
        server_name fivecoresolutions.com www.fivecoresolutions.com;  # Substitua pelo seu domínio

        # Certificados SSL (Let's Encrypt ou outros)
        ssl_certificate /etc/ssl/fullchain.pem;
        ssl_certificate_key /etc/ssl/privkey.pem;
        # include /etc/letsencrypt/options-ssl-nginx.conf;
        #ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem;

        ssl_session_cache shared:le_nginx_SSL:10m;
        ssl_session_timeout 1440m;
        ssl_session_tickets off;

        ssl_protocols TLSv1.2 TLSv1.3;
        ssl_prefer_server_ciphers off;

        ssl_ciphers 'ECDHE+AESGCM:ECDHE+CHACHA20';

        # Ativa HSTS (Strict Transport Security) para forçar o HTTPS
        add_header Strict-Transport-Security "max-age=31536000; includeSubDomains; preload" always;

        # Configuração para o Frontend (Next.js)
        location / {
            proxy_pass http://frontend_prod:3000;  # Nome do serviço no docker-compose.prod.yml
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Configuração para o Backend (NestJS API)
        location /api/ {
            # Remove /api do path antes de passar para o backend
            rewrite ^/api/(.*)$ /$1 break;

            proxy_pass http://backend_prod:3001;  # Nome do serviço no docker-compose.prod.yml
            proxy_http_version 1.1;
            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection 'upgrade';
            proxy_set_header Host $host;
            proxy_cache_bypass $http_upgrade;
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Forwarded-Proto $scheme;
        }

        # Logs
        access_log /var/log/nginx/access.log;
        error_log /var/log/nginx/error.log;

        # Limites de tamanho de upload
        client_max_body_size 10M;
    }
}
